version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "+08:00"
