spring:
  application:
    name: easy-captcha-demo

  data:
    redis:
      host: 127.0.0.1
      port: 6379

# 验证码相关配置
easy-captcha:
  enabled: true
  width: 200
  height: 50
  captcha-type: arithmetic_captcha
  captcha-length: 4
  char-type: default
  font: actionj
  difficulty: easy
