name: Automerge Dependabot PR

on:
  pull_request:
    types: [ labeled, synchronize, opened, ready_for_review ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name contains 'dependencies'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable GitHub auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
